package com.dus.dusframe.testbeanutils;

public class CcmsT303 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MSGID
     *
     * @mbg.generated
     */
    private String msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MESGDIRECTION
     *
     * @mbg.generated
     */
    private String mesgdirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.PLATFLOWNO
     *
     * @mbg.generated
     */
    private String platflowno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.PLATDATE
     *
     * @mbg.generated
     */
    private String platdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.PLATTIME
     *
     * @mbg.generated
     */
    private String plattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MESGTYPE
     *
     * @mbg.generated
     */
    private String mesgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MESGID
     *
     * @mbg.generated
     */
    private String mesgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MESGREFID
     *
     * @mbg.generated
     */
    private String mesgrefid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.CREDTTM
     *
     * @mbg.generated
     */
    private String credttm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.INSTGDRCTPTY
     *
     * @mbg.generated
     */
    private String instgdrctpty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.INSTGPTY
     *
     * @mbg.generated
     */
    private String instgpty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.INSTDDRCTPTY
     *
     * @mbg.generated
     */
    private String instddrctpty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.INSTDPTY
     *
     * @mbg.generated
     */
    private String instdpty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.SYSTEMCODE
     *
     * @mbg.generated
     */
    private String systemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MSGCNTT
     *
     * @mbg.generated
     */
    private String msgcntt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.RESCODE
     *
     * @mbg.generated
     */
    private String rescode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.RESINFO
     *
     * @mbg.generated
     */
    private String resinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.CHANNELCGY
     *
     * @mbg.generated
     */
    private String channelcgy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.CHANNELCODE
     *
     * @mbg.generated
     */
    private String channelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.MULTIENTITY
     *
     * @mbg.generated
     */
    private String multientity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.BUSIDATE
     *
     * @mbg.generated
     */
    private String busidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.DACVERF
     *
     * @mbg.generated
     */
    private String dacverf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.TMS
     *
     * @mbg.generated
     */
    private Object tms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCMS_T303.VNO
     *
     * @mbg.generated
     */
    private Integer vno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MSGID
     *
     * @return the value of CCMS_T303.MSGID
     *
     * @mbg.generated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MSGID
     *
     * @param msgid the value for CCMS_T303.MSGID
     *
     * @mbg.generated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MESGDIRECTION
     *
     * @return the value of CCMS_T303.MESGDIRECTION
     *
     * @mbg.generated
     */
    public String getMesgdirection() {
        return mesgdirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MESGDIRECTION
     *
     * @param mesgdirection the value for CCMS_T303.MESGDIRECTION
     *
     * @mbg.generated
     */
    public void setMesgdirection(String mesgdirection) {
        this.mesgdirection = mesgdirection == null ? null : mesgdirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.PLATFLOWNO
     *
     * @return the value of CCMS_T303.PLATFLOWNO
     *
     * @mbg.generated
     */
    public String getPlatflowno() {
        return platflowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.PLATFLOWNO
     *
     * @param platflowno the value for CCMS_T303.PLATFLOWNO
     *
     * @mbg.generated
     */
    public void setPlatflowno(String platflowno) {
        this.platflowno = platflowno == null ? null : platflowno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.PLATDATE
     *
     * @return the value of CCMS_T303.PLATDATE
     *
     * @mbg.generated
     */
    public String getPlatdate() {
        return platdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.PLATDATE
     *
     * @param platdate the value for CCMS_T303.PLATDATE
     *
     * @mbg.generated
     */
    public void setPlatdate(String platdate) {
        this.platdate = platdate == null ? null : platdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.PLATTIME
     *
     * @return the value of CCMS_T303.PLATTIME
     *
     * @mbg.generated
     */
    public String getPlattime() {
        return plattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.PLATTIME
     *
     * @param plattime the value for CCMS_T303.PLATTIME
     *
     * @mbg.generated
     */
    public void setPlattime(String plattime) {
        this.plattime = plattime == null ? null : plattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MESGTYPE
     *
     * @return the value of CCMS_T303.MESGTYPE
     *
     * @mbg.generated
     */
    public String getMesgtype() {
        return mesgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MESGTYPE
     *
     * @param mesgtype the value for CCMS_T303.MESGTYPE
     *
     * @mbg.generated
     */
    public void setMesgtype(String mesgtype) {
        this.mesgtype = mesgtype == null ? null : mesgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MESGID
     *
     * @return the value of CCMS_T303.MESGID
     *
     * @mbg.generated
     */
    public String getMesgid() {
        return mesgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MESGID
     *
     * @param mesgid the value for CCMS_T303.MESGID
     *
     * @mbg.generated
     */
    public void setMesgid(String mesgid) {
        this.mesgid = mesgid == null ? null : mesgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MESGREFID
     *
     * @return the value of CCMS_T303.MESGREFID
     *
     * @mbg.generated
     */
    public String getMesgrefid() {
        return mesgrefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MESGREFID
     *
     * @param mesgrefid the value for CCMS_T303.MESGREFID
     *
     * @mbg.generated
     */
    public void setMesgrefid(String mesgrefid) {
        this.mesgrefid = mesgrefid == null ? null : mesgrefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.CREDTTM
     *
     * @return the value of CCMS_T303.CREDTTM
     *
     * @mbg.generated
     */
    public String getCredttm() {
        return credttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.CREDTTM
     *
     * @param credttm the value for CCMS_T303.CREDTTM
     *
     * @mbg.generated
     */
    public void setCredttm(String credttm) {
        this.credttm = credttm == null ? null : credttm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.INSTGDRCTPTY
     *
     * @return the value of CCMS_T303.INSTGDRCTPTY
     *
     * @mbg.generated
     */
    public String getInstgdrctpty() {
        return instgdrctpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.INSTGDRCTPTY
     *
     * @param instgdrctpty the value for CCMS_T303.INSTGDRCTPTY
     *
     * @mbg.generated
     */
    public void setInstgdrctpty(String instgdrctpty) {
        this.instgdrctpty = instgdrctpty == null ? null : instgdrctpty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.INSTGPTY
     *
     * @return the value of CCMS_T303.INSTGPTY
     *
     * @mbg.generated
     */
    public String getInstgpty() {
        return instgpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.INSTGPTY
     *
     * @param instgpty the value for CCMS_T303.INSTGPTY
     *
     * @mbg.generated
     */
    public void setInstgpty(String instgpty) {
        this.instgpty = instgpty == null ? null : instgpty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.INSTDDRCTPTY
     *
     * @return the value of CCMS_T303.INSTDDRCTPTY
     *
     * @mbg.generated
     */
    public String getInstddrctpty() {
        return instddrctpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.INSTDDRCTPTY
     *
     * @param instddrctpty the value for CCMS_T303.INSTDDRCTPTY
     *
     * @mbg.generated
     */
    public void setInstddrctpty(String instddrctpty) {
        this.instddrctpty = instddrctpty == null ? null : instddrctpty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.INSTDPTY
     *
     * @return the value of CCMS_T303.INSTDPTY
     *
     * @mbg.generated
     */
    public String getInstdpty() {
        return instdpty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.INSTDPTY
     *
     * @param instdpty the value for CCMS_T303.INSTDPTY
     *
     * @mbg.generated
     */
    public void setInstdpty(String instdpty) {
        this.instdpty = instdpty == null ? null : instdpty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.SYSTEMCODE
     *
     * @return the value of CCMS_T303.SYSTEMCODE
     *
     * @mbg.generated
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.SYSTEMCODE
     *
     * @param systemcode the value for CCMS_T303.SYSTEMCODE
     *
     * @mbg.generated
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode == null ? null : systemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.REMARK
     *
     * @return the value of CCMS_T303.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.REMARK
     *
     * @param remark the value for CCMS_T303.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MSGCNTT
     *
     * @return the value of CCMS_T303.MSGCNTT
     *
     * @mbg.generated
     */
    public String getMsgcntt() {
        return msgcntt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MSGCNTT
     *
     * @param msgcntt the value for CCMS_T303.MSGCNTT
     *
     * @mbg.generated
     */
    public void setMsgcntt(String msgcntt) {
        this.msgcntt = msgcntt == null ? null : msgcntt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.RESCODE
     *
     * @return the value of CCMS_T303.RESCODE
     *
     * @mbg.generated
     */
    public String getRescode() {
        return rescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.RESCODE
     *
     * @param rescode the value for CCMS_T303.RESCODE
     *
     * @mbg.generated
     */
    public void setRescode(String rescode) {
        this.rescode = rescode == null ? null : rescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.RESINFO
     *
     * @return the value of CCMS_T303.RESINFO
     *
     * @mbg.generated
     */
    public String getResinfo() {
        return resinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.RESINFO
     *
     * @param resinfo the value for CCMS_T303.RESINFO
     *
     * @mbg.generated
     */
    public void setResinfo(String resinfo) {
        this.resinfo = resinfo == null ? null : resinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.CHANNELCGY
     *
     * @return the value of CCMS_T303.CHANNELCGY
     *
     * @mbg.generated
     */
    public String getChannelcgy() {
        return channelcgy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.CHANNELCGY
     *
     * @param channelcgy the value for CCMS_T303.CHANNELCGY
     *
     * @mbg.generated
     */
    public void setChannelcgy(String channelcgy) {
        this.channelcgy = channelcgy == null ? null : channelcgy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.CHANNELCODE
     *
     * @return the value of CCMS_T303.CHANNELCODE
     *
     * @mbg.generated
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.CHANNELCODE
     *
     * @param channelcode the value for CCMS_T303.CHANNELCODE
     *
     * @mbg.generated
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode == null ? null : channelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.MULTIENTITY
     *
     * @return the value of CCMS_T303.MULTIENTITY
     *
     * @mbg.generated
     */
    public String getMultientity() {
        return multientity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.MULTIENTITY
     *
     * @param multientity the value for CCMS_T303.MULTIENTITY
     *
     * @mbg.generated
     */
    public void setMultientity(String multientity) {
        this.multientity = multientity == null ? null : multientity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.BUSIDATE
     *
     * @return the value of CCMS_T303.BUSIDATE
     *
     * @mbg.generated
     */
    public String getBusidate() {
        return busidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.BUSIDATE
     *
     * @param busidate the value for CCMS_T303.BUSIDATE
     *
     * @mbg.generated
     */
    public void setBusidate(String busidate) {
        this.busidate = busidate == null ? null : busidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.DACVERF
     *
     * @return the value of CCMS_T303.DACVERF
     *
     * @mbg.generated
     */
    public String getDacverf() {
        return dacverf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.DACVERF
     *
     * @param dacverf the value for CCMS_T303.DACVERF
     *
     * @mbg.generated
     */
    public void setDacverf(String dacverf) {
        this.dacverf = dacverf == null ? null : dacverf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.TMS
     *
     * @return the value of CCMS_T303.TMS
     *
     * @mbg.generated
     */
    public Object getTms() {
        return tms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.TMS
     *
     * @param tms the value for CCMS_T303.TMS
     *
     * @mbg.generated
     */
    public void setTms(Object tms) {
        this.tms = tms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCMS_T303.VNO
     *
     * @return the value of CCMS_T303.VNO
     *
     * @mbg.generated
     */
    public Integer getVno() {
        return vno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCMS_T303.VNO
     *
     * @param vno the value for CCMS_T303.VNO
     *
     * @mbg.generated
     */
    public void setVno(Integer vno) {
        this.vno = vno;
    }

	@Override
	public String toString() {
		return "CcmsT303 [msgid=" + msgid + ", mesgdirection=" + mesgdirection + ", platflowno=" + platflowno
				+ ", platdate=" + platdate + ", plattime=" + plattime + ", mesgtype=" + mesgtype + ", mesgid=" + mesgid
				+ ", mesgrefid=" + mesgrefid + ", credttm=" + credttm + ", instgdrctpty=" + instgdrctpty + ", instgpty="
				+ instgpty + ", instddrctpty=" + instddrctpty + ", instdpty=" + instdpty + ", systemcode=" + systemcode
				+ ", remark=" + remark + ", msgcntt=" + msgcntt + ", rescode=" + rescode + ", resinfo=" + resinfo
				+ ", channelcgy=" + channelcgy + ", channelcode=" + channelcode + ", multientity=" + multientity
				+ ", busidate=" + busidate + ", dacverf=" + dacverf + ", tms=" + tms + ", vno=" + vno + "]";
	}
    
    
}